logging:
  level:
    root: debug
    org:
      springframework:
        jdbc: debug
        transaction: info
        data: debug
      hibernate: info

server:
  port: 8080

spring:
  datasource:
    url: host
    username: username
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
