logging:
  level:
    root: error
    org:
      springframework:
        jdbc: error
        transaction: error
        data: error
      hibernate: error

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-steep-frost-a1ukei8f.ap-southeast-1.aws.neon.tech/postgre-db
    username: postgre-db_owner
    password: OLfTMz0j6oSc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
