CREATE SEQUENCE SEQ_ACCOUNT START WITH 1 INCREMENT BY 1;
CREATE TABLE ACCOUNT
(
    ID            NUMERIC(20, 0) DEFAULT NEXTVAL('SEQ_ACCOUNT') NOT NULL,
    USERNAME      VARCHAR(100),
    PASSWORD      VARCHAR(255),
    FIRST_NAME    VARCHAR(100),
    LAST_NAME     VARCHAR(100),
    BIRTH_DATE    DATE,
    CREATED_DATE  DATE,
    CREATED_ID    NUMERIC(20, 0),
    UPDATED_DATE  DATE,
    UPDATED_ID    NUMERIC(20, 0),
    APPROVED_DATE DATE,
    APPROVED_ID   NUMERIC(20, 0),
    DELETED_DATE  DATE,
    DELETED_ID    NUMERIC(20, 0) DEFAULT 0,
    IS_ACTIVED    NUMERIC(1, 0),
    STATUS        NUMERIC(1, 0),
    FROM_DATE     DATE,
    TO_DATE       DATE,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ROLE START WITH 1 INCREMENT BY 1;
CREATE TABLE ROLE
(
    ID               NUMERIC(20, 0) DEFAULT NEXTVAL('SEQ_ROLE') NOT NULL,
    ROLE_NAME        VARCHAR(100),
    ROLE_DESCRIPTION VARCHAR(255),
    CREATED_DATE     DATE,
    CREATED_ID       NUMERIC(20, 0),
    UPDATED_DATE     DATE,
    UPDATED_ID       NUMERIC(20, 0),
    APPROVED_DATE    DATE,
    APPROVED_ID      NUMERIC(20, 0),
    DELETED_DATE     DATE,
    DELETED_ID       NUMERIC(20, 0) DEFAULT 0,
    IS_ACTIVED       NUMERIC(1, 0),
    STATUS           NUMERIC(1, 0),
    FROM_DATE        DATE,
    TO_DATE          DATE,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_PERMISSION START WITH 1 INCREMENT BY 1;
CREATE TABLE PERMISSION
(
    ID                     NUMERIC(20, 0) DEFAULT NEXTVAL('SEQ_PERMISSION') NOT NULL,
    PERMISSION_NAME        VARCHAR(100),
    PERMISSION_DESCRIPTION VARCHAR(255),
    CREATED_DATE           DATE,
    CREATED_ID             NUMERIC(20, 0),
    UPDATED_DATE           DATE,
    UPDATED_ID             NUMERIC(20, 0),
    APPROVED_DATE          DATE,
    APPROVED_ID            NUMERIC(20, 0),
    DELETED_DATE           DATE,
    DELETED_ID             NUMERIC(20, 0) DEFAULT 0,
    IS_ACTIVED             NUMERIC(1, 0),
    STATUS                 NUMERIC(1, 0),
    FROM_DATE              DATE,
    TO_DATE                DATE,
    CONSTRAINT PK_PERMISSION PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ACCOUNT_ROLES START WITH 1 INCREMENT BY 1;
CREATE TABLE ACCOUNT_ROLES
(
    ID            NUMERIC(20, 0) DEFAULT NEXTVAL('SEQ_ACCOUNT_ROLES') NOT NULL,
    ACCOUNT_ID    NUMERIC(20, 0),
    ROLE_ID       NUMERIC(20, 0),
    CREATED_DATE  DATE,
    CREATED_ID    NUMERIC(20, 0),
    UPDATED_DATE  DATE,
    UPDATED_ID    NUMERIC(20, 0),
    APPROVED_DATE DATE,
    APPROVED_ID   NUMERIC(20, 0),
    DELETED_DATE  DATE,
    DELETED_ID    NUMERIC(20, 0) DEFAULT 0,
    IS_ACTIVED    NUMERIC(1, 0),
    STATUS        NUMERIC(1, 0),
    FROM_DATE     DATE,
    TO_DATE       DATE,
    CONSTRAINT PK_ACCOUNT_ROLES PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ROLE_PERMISSIONS START WITH 1 INCREMENT BY 1;
CREATE TABLE ROLE_PERMISSIONS
(
    ID            NUMERIC(20, 0) DEFAULT NEXTVAL('SEQ_ROLE_PERMISSIONS') NOT NULL,
    ROLE_ID       NUMERIC(20, 0),
    PERMISSION_ID NUMERIC(20, 0),
    CREATED_DATE  DATE,
    CREATED_ID    NUMERIC(20, 0),
    UPDATED_DATE  DATE,
    UPDATED_ID    NUMERIC(20, 0),
    APPROVED_DATE DATE,
    APPROVED_ID   NUMERIC(20, 0),
    DELETED_DATE  DATE,
    DELETED_ID    NUMERIC(20, 0) DEFAULT 0,
    IS_ACTIVED    NUMERIC(1, 0),
    STATUS        NUMERIC(1, 0),
    FROM_DATE     DATE,
    TO_DATE       DATE,
    CONSTRAINT PK_ROLE_PERMISSIONS PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_INVALIDATE_TOKEN START WITH 1 INCREMENT BY 1;
CREATE TABLE INVALIDATE_TOKEN
(
    ID            NUMERIC(20, 0) DEFAULT NEXTVAL('SEQ_INVALIDATE_TOKEN') NOT NULL,
    CODE          VARCHAR(500),
    EXPIRY_TIME   DATE,
    CREATED_DATE  DATE,
    CREATED_ID    NUMERIC(20, 0),
    UPDATED_DATE  DATE,
    UPDATED_ID    NUMERIC(20, 0),
    APPROVED_DATE DATE,
    APPROVED_ID   NUMERIC(20, 0),
    DELETED_DATE  DATE,
    DELETED_ID    NUMERIC(20, 0) DEFAULT 0,
    IS_ACTIVED    NUMERIC(1, 0),
    STATUS        NUMERIC(1, 0),
    FROM_DATE     DATE,
    TO_DATE       DATE,
    CONSTRAINT PK_INVALIDATE_TOKEN PRIMARY KEY (ID)
);

