version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE.USERNAME}/${IMAGE.PROJECT_NAME}:${IMAGE.VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - ${NETWORK_NAME}

networks:
  app-net:
    name: ${NETWORK_NAME}