pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker-hub')
        IMAGE_NAME = 'lenhuthao/microservices'
        IMAGE_TAG = '0.0.1'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('api') {
                    script {
                        sh 'ls'
                        sh 'start Docker-build.bat'
                    }
                }
            }
        }
    }
}
